from django.urls import path

from .views import (
    ChangePasswordView,
    CompleteTaskView,
    CurrentUserView,
    DeleteUserView,
    LoginView,
    LatestAlertView,
    LogoutView,
    PendingUsersView,
    RecoveryAdminView,
    RecoveryStatusView,
    SensorDataView,
    SignupView,
    TodayTasksView,
    TasksView,
    UpdateUserRoleView,
    UpdateUserStatusView,
    UpdateUserApprovalView,
    UsersListView,
    UserSessionsView,
)

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("recovery/status/", RecoveryStatusView.as_view(), name="recovery-status"),
    path("recovery/promote-admin/", RecoveryAdminView.as_view(), name="recovery-promote-admin"),
    path("signup/", SignupView.as_view(), name="signup"),
    path("user/", CurrentUserView.as_view(), name="current-user"),
    path("user/change-password/", ChangePasswordView.as_view(), name="change-password"),
    path("alerts/latest/", LatestAlertView.as_view(), name="latest-alert"),
    path("sensor-data/", SensorDataView.as_view(), name="sensor-data"),
    # Alias for legacy/client usage: allow /api/sensors/ to work as well
    path("sensors/", SensorDataView.as_view(), name="sensors-alias"),
    path("tasks/", TasksView.as_view(), name="tasks"),
    path("tasks/today/", TodayTasksView.as_view(), name="today-tasks"),
    path("tasks/<int:pk>/complete/", CompleteTaskView.as_view(), name="complete-task"),
    path("sessions/", UserSessionsView.as_view(), name="user-sessions"),
    path("users/", UsersListView.as_view(), name="users-list"),
    path("users/<int:pk>/role/", UpdateUserRoleView.as_view(), name="update-user-role"),
    path("users/<int:pk>/status/", UpdateUserStatusView.as_view(), name="update-user-status"),
    path("users/<int:pk>/", DeleteUserView.as_view(), name="delete-user"),
    path("users/pending", PendingUsersView.as_view(), name="pending-users-no-slash"),
    path("users/pending/", PendingUsersView.as_view(), name="pending-users"),
    path("users/<int:pk>/<str:action>", UpdateUserApprovalView.as_view(), name="update-user-approval-no-slash"),
    path("users/<int:pk>/<str:action>/", UpdateUserApprovalView.as_view(), name="update-user-approval"),
]
